 * Serving Flask app "service_app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:9999/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
127.0.0.1 - - [21/Jul/2019 18:38:17] "POST /GeoVideoApplication/upload HTTP/1.0" 400 -
127.0.0.1 - - [21/Jul/2019 18:38:25] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 18:38:38] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 404 -
127.0.0.1 - - [21/Jul/2019 18:40:06] "GET /GeoVideoApplication/speechtotext?files=male HTTP/1.0" 405 -
 * Detected change in '/home/vitthals/speech_to_text/speech_to_text/conf/service_app.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
 * Serving Flask app "service_app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:9999/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
127.0.0.1 - - [21/Jul/2019 18:45:28] "POST /GeoVideoApplication/ping/ HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 18:45:30] "POST /GeoVideoApplication/ping/ HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 18:48:06] "POST /GeoVideoApplication/ping/ HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 18:48:26] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 18:48:49] "GET /GeoVideoApplication/test?files=male3 HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:32:32] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:32:32] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:32:32] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
127.0.0.1 - - [21/Jul/2019 19:33:15] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:33:17] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:33:18] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
127.0.0.1 - - [21/Jul/2019 19:33:50] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:33:50] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:33:50] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
127.0.0.1 - - [21/Jul/2019 19:34:44] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:34:45] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:34:45] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
127.0.0.1 - - [21/Jul/2019 19:45:25] "GET /GeoVideoApplication/test?files=male3 HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 19:49:47] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 20:20:48] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 20:20:51] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 20:20:52] "POST /GeoVideoApplication/test?files=1563740273341 HTTP/1.0" 405 -
127.0.0.1 - - [21/Jul/2019 20:22:09] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 20:22:09] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [21/Jul/2019 20:22:10] "POST /GeoVideoApplication/test?files=1563740273341 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 00:34:14] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 00:34:15] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 00:34:15] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 05:44:48] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 05:44:49] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 05:44:49] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
 * Detected change in '/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py', reloading
 * Restarting with stat
Traceback (most recent call last):
  File "/home/vitthals/speech_to_text/speech_to_text/conf/service_app.py", line 5, in <module>
    from speech_to_text.service_apis.speech_to_text import SpeechToText
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 32
    fpathlist = fileName.split("\")
                                  ^
SyntaxError: EOL while scanning string literal
 * Serving Flask app "service_app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:9999/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
127.0.0.1 - - [22/Jul/2019 09:27:25] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 63, in get
    responseFinal = printit(files)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 39, in printit
    with sr.AudioFile(audio) as source:
  File "/home/vitthals/venv/lib/python2.7/site-packages/speech_recognition/__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 160, in __init__
    f = __builtin__.open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'male3.wav'
127.0.0.1 - - [22/Jul/2019 09:27:36] "POST /GeoVideoApplication/ping/ HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:27:43] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:27:47] "POST /GeoVideoApplication/ping/ HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:27:52] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 63, in get
    responseFinal = printit(files)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 39, in printit
    with sr.AudioFile(audio) as source:
  File "/home/vitthals/venv/lib/python2.7/site-packages/speech_recognition/__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 160, in __init__
    f = __builtin__.open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'male3.wav'
127.0.0.1 - - [22/Jul/2019 09:27:57] "GET /GeoVideoApplication/test%3ffiles=male HTTP/1.0" 404 -
127.0.0.1 - - [22/Jul/2019 09:27:58] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 63, in get
    responseFinal = printit(files)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 39, in printit
    with sr.AudioFile(audio) as source:
  File "/home/vitthals/venv/lib/python2.7/site-packages/speech_recognition/__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 160, in __init__
    f = __builtin__.open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'male3.wav'
127.0.0.1 - - [22/Jul/2019 09:28:08] "GET /GeoVideoApplication/test%3ffiles=male HTTP/1.0" 404 -
127.0.0.1 - - [22/Jul/2019 09:28:17] "GET /GeoVideoApplication/test%3ffiles=male HTTP/1.0" 404 -
127.0.0.1 - - [22/Jul/2019 09:28:30] "GET /GeoVideoApplication/test%3ffiles=male HTTP/1.0" 404 -
127.0.0.1 - - [22/Jul/2019 09:28:40] "GET /GeoVideoApplication/test?files=male3 HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 63, in get
    responseFinal = printit(files)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 39, in printit
    with sr.AudioFile(audio) as source:
  File "/home/vitthals/venv/lib/python2.7/site-packages/speech_recognition/__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 160, in __init__
    f = __builtin__.open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'male3.wav'
127.0.0.1 - - [22/Jul/2019 09:28:48] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 500 -
Traceback (most recent call last):
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2463, in __call__
    return self.wsgi_app(environ, start_response)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2449, in wsgi_app
    response = self.handle_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1866, in handle_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 2446, in wsgi_app
    response = self.full_dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1951, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 269, in error_router
    return original_handler(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1820, in handle_user_exception
    reraise(exc_type, exc_value, tb)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 266, in error_router
    return self.handle_error(e)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1949, in full_dispatch_request
    rv = self.dispatch_request()
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/app.py", line 1935, in dispatch_request
    return self.view_functions[rule.endpoint](**req.view_args)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 458, in wrapper
    resp = resource(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask/views.py", line 89, in view
    return self.dispatch_request(*args, **kwargs)
  File "/home/vitthals/venv/lib/python2.7/site-packages/flask_restful/__init__.py", line 573, in dispatch_request
    resp = meth(*args, **kwargs)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 63, in get
    responseFinal = printit(files)
  File "/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py", line 39, in printit
    with sr.AudioFile(audio) as source:
  File "/home/vitthals/venv/lib/python2.7/site-packages/speech_recognition/__init__.py", line 203, in __enter__
    self.audio_reader = wave.open(self.filename_or_fileobject, "rb")
  File "/usr/lib/python2.7/wave.py", line 511, in open
    return Wave_read(f)
  File "/usr/lib/python2.7/wave.py", line 160, in __init__
    f = __builtin__.open(f, 'rb')
IOError: [Errno 2] No such file or directory: 'male3.wav'
 * Detected change in '/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py', reloading
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
 * Serving Flask app "service_app" (lazy loading)
 * Environment: production
   WARNING: This is a development server. Do not use it in a production deployment.
   Use a production WSGI server instead.
 * Debug mode: on
 * Running on http://localhost:9999/ (Press CTRL+C to quit)
 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
127.0.0.1 - - [22/Jul/2019 09:32:51] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:33:34] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:36:59] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:36:59] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:37:00] "POST /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 09:39:36] "GET /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 09:47:45] "GET /GeoVideoApplication/test?files=male HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 10:58:13] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 10:58:15] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 10:58:15] "POST /GeoVideoApplication/test?files=1563792884816 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 10:58:35] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 10:58:37] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 10:58:37] "POST /GeoVideoApplication/test?files=1563792884816 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 11:26:44] "GET /GeoVideoApplication/test?files=1563737479357 HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 11:39:23] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 11:39:26] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 11:39:46] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 11:39:48] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 11:39:48] "POST /GeoVideoApplication/test?files=1563795442495 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 12:05:32] "GET /GeoVideoApplication/test?files=1563740273341 HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:06:15] "GET /GeoVideoApplication/test?files=1563795442495 HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:09:21] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:09:21] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:09:21] "POST /GeoVideoApplication/test?files=1563797288095 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 12:09:47] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:09:48] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:09:49] "POST /GeoVideoApplication/test?files=1563797288095 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 12:10:06] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:10:06] "POST /GeoVideoApplication/upload HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:10:06] "POST /GeoVideoApplication/test?files=1563797288095 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 12:14:42] "POST /GeoVideoApplication/test?files=1563795442495 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 12:14:44] "POST /GeoVideoApplication/test?files=1563795442495 HTTP/1.0" 405 -
127.0.0.1 - - [22/Jul/2019 12:16:40] "GET /GeoVideoApplication/ping/ HTTP/1.0" 200 -
127.0.0.1 - - [22/Jul/2019 12:16:44] "GET /GeoVideoApplication/ping/ HTTP/1.0" 200 -
 * Detected change in '/home/vitthals/speech_to_text/speech_to_text/service_apis/speech_to_text.py', reloading
************* ImmutableMultiDict([])
---------------> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Connection: close
Postman-Token: 7cf07c04-8216-984e-0026-cec71bc1bb9c
Host: 127.0.0.1:9999
Cache-Control: no-cache
Accept: */*
Accept-Language: en-US,en;q=0.9
Accept-Encoding: gzip, deflate


************* ImmutableMultiDict([])
---------------> User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/75.0.3770.142 Safari/537.36
Connection: close
Postman-Token: 781f3770-cdcd-7eb1-1b98-a40fa4e9e01f
Host: 127.0.0.1:9999
Cache-Control: no-cache
Accept: */*
Accept-Language: en-US,en;q=0.9
Accept-Encoding: gzip, deflate


 * Restarting with stat
 * Debugger is active!
 * Debugger PIN: 117-343-704
